### ISSUE TITLE
Build Manage Roles Page

### ISSUE THREAD

**Issue by kpwags** [kpwags/digital-family-cookbook#24]
## Tasks To Do
- [x] Build React Unit Tests
- [x] Build C# Unit Tests
- [x] Lock Down Page
- [x] Add Warning on Page
